# 服务器设定
server:
  #端口
  port: 8703

# 指定当前eureka客户端的注册地址，也就是eureka服务的提供方，当前配置的服务的注册服务方
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
    register-with-eureka: false #自身 不在向eureka注册
    fetch-registry: false  #启动时禁用client的注册
  instance:
    hostname: localhost
    server:
      port: 8702


spring:
  #指定应用名称
  application:
    name: config

  #指定git配置地址
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://github.com/RuiDer/ExpressServiceConfig/
          # 配置仓库地址下相对搜索地址
          search-paths: config-repo
          # 用户名
          username: RuiDer
          #密码
          password: Mhd080210
