# 服务提供方
server:
  port: 8802

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
  instance:
    hostname: localhost
    server:
      port: 8702

#当前服务名称
spring:
  application:
    name: order-service
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:orderMapper.xml

