# 服务器设定
server:
  #端口
  port: 8700

# 指定当前eureka客户端的注册地址，也就是eureka服务的提供方，当前配置的服务的注册服务方
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
    register-with-eureka: false #自身 不在向eureka注册
    fetch-registry: true  #启动时启用client的注册
  instance:
    hostname: localhost
    server:
      port: 8702
#指定应用名称
spring:
  application:
    name: api-zuul

# 开启拉取eureka服务实例列表
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
  eureka:
    enabled: true
# 路由规则配置
# 面向请求路由配置

#zuul:
#  routes:
#    api-hello-url:
#      path: /api-hello-url/**
#      url: http://loZucalhost:8701/Hello/helloService

#面向服务配置

zuul:
  routes:

    # Hello路由规则配置
    api-hello:
      path: /api-hello-url/**
      serviceId: Ribbon-Service

    # User请求路由规则配置
    api-user:
      path: /api-user-url/**
      serviceId: Ribbon-Service

    # order请求路由配置
    api-order:
      path: /api-orderInfo-url/**
      serviceId: Ribbon-Service

    # comment请求路由配置
    api-comment:
      path: /api-commentInfo-url/**
      serviceId: Ribbon-Service

    # comment请求路由配置
    api-feedback:
      path: /api-feedbackInfo-url/**
      serviceId: Ribbon-Service

    # weChatApp请求路由配置
    api-wechatapp:
      path: /api-wechatapp-url/**
      serviceId: Ribbon-Service



