# 服务提供方
server:
  port: 8801


#swagger
swagger:
  enabled: true

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
  instance:
    hostname: localhost
    server:
      port: 8702


spring:
  #当前服务名称
  application:
    name: user-service

  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.basic
  mapper-locations: classpath:userMapper.xml