# 服务提供方
#server.port=8801
server:
  port: 8801

eureka:
  client:
    service-url: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
  instance:
    hostname: localhost
    server:
      port: 8702


#  eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
#eureka.instance.hostname=localhost
#eureka.instance.server.port=8702

spring:
  application:
    name: user-service
  session:
    store-type: none

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 1111


#  spring.application.name=user-service
#spring.session.store-type=none
#spring.datasource.url=jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=1111
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#

#mybatis.type-aliases-package=com.basic
#mybatis.mapper-locations=classpath:userMapper.xml

mybatis:
  type-aliases-package: com.basic
  mapper-locations: classpath:userMapper.xml


#swagger

# 指定当前eureka客户端的注册地址,
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
#  instance:
#    hostname: localhost
#    server:
#      port: 8702


#spring:
#  #当前服务名称
#  application:
#    name: user-service
#
#  session:
#    store-type: none
#
#  #数据源配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
#    username: root
#    password: 1111
#    driver-class-name: com.mysql.jdbc.Driver


#mybatis:
#  type-aliases-package: com.basic
#  mapper-locations: classpath:userMapper.xml