# 服务提供方
server:
  port: 8804

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
  instance:
    hostname: localhost
    server:
      port: 8702

#当前服务名称
spring:
  application:
    name: feedback-service