#服务客户端端口
server:
  port: 8804

#指定当前eureka客户端的注册地址
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
  instance:
    hostname: localhost
    server:
      port: 8702



spring:
  application:
    name: wechatapp-service

  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://localhost:3306/ExpressService?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect