# 服务消费方
server:
  port: 8701

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka
  instance:
    hostname: localhost
    server:
      port: 8702

#当前服务名称
spring:
  application:
    name: Ribbon-Service


#断路器配置
feign:
  hystrix:
    enabled: true

#日志配置
logging:
  level:
    web: TRACE
    org:
      springframework:
        web: TRACE